name: Generate Tokens and Create PR

on:
  push:
    branches:
      - tokens-test

jobs:
  generate_tokens:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: tokens-test
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Generate app tokens
        run: node generate-tokens.js
        env:
          JSON_FILE_PATH: tokens.json
          OUTPUT_FILE_PATH: app-tokens.css

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: design-tokens/patch
          branch-suffix: timestamp
          base: development
          delete-branch: true
          title: "feat: Update design tokens from tokens-test"
          body: "This pull request automatically updates the design tokens based on the latest changes in the `tokens-test` branch."
          commit-message: "feat: Auto-generated app tokens"
